# Generated by Django 4.2.1 on 2023-06-09 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='concluido',
        ),
        migrations.RemoveField(
            model_name='post',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='prioridade',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 9, 13, 16, 5, 60929, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='descricao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
