# Generated by Django 4.2.1 on 2023-06-10 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_area_post_likes_alter_post_data_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='nome',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 22, 19, 30, 516406, tzinfo=datetime.timezone.utc)),
        ),
    ]
