# Generated by Django 4.2.1 on 2023-06-10 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 22, 25, 48, 833039, tzinfo=datetime.timezone.utc)),
        ),
    ]
