# Generated by Django 4.2.1 on 2023-06-10 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_post_comentarios_comentario_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.IntegerField(default='LifeStyle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 23, 25, 34, 615957, tzinfo=datetime.timezone.utc)),
        ),
    ]
