# Generated by Django 4.2.1 on 2023-06-10 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_area_nome_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.IntegerField(default='LifeStyle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 23, 28, 8, 26598, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
