# Generated by Django 4.2.1 on 2023-06-10 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_post_area_alter_post_data_delete_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(default='LifeStyle', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 23, 30, 6, 298730, tzinfo=datetime.timezone.utc)),
        ),
    ]
