# Generated by Django 4.2.1 on 2023-06-14 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_post_area_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('orientador', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 14, 9, 31, 752466, tzinfo=datetime.timezone.utc)),
        ),
    ]
