# Generated by Django 4.2.1 on 2023-06-14 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_projeto_projetos_alter_post_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projetos',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 14, 18, 35, 44702, tzinfo=datetime.timezone.utc)),
        ),
    ]
