# Generated by Django 4.2.1 on 2023-06-14 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_delete_projetos_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='laboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('lab', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 15, 9, 42, 933228, tzinfo=datetime.timezone.utc)),
        ),
    ]
