# Generated by Django 4.2.1 on 2023-06-14 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 18, 29, 20, 225199, tzinfo=datetime.timezone.utc)),
        ),
    ]
