# Generated by Django 4.2.1 on 2023-06-14 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_post_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pagina_lusofona', models.URLField(blank=True)),
                ('pagina_linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 23, 25, 35, 183927, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('semestre', models.PositiveIntegerField()),
                ('ects', models.PositiveIntegerField()),
                ('ano_letivo_frequentado', models.PositiveIntegerField()),
                ('topicos_abordados', models.TextField()),
                ('professores', models.ManyToManyField(related_name='cadeiras', to='portfolio.pessoa')),
            ],
        ),
    ]
