# Generated by Django 4.2.1 on 2023-06-14 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_pessoa_alter_post_data_cadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='cadeiras', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='topicos_abordados',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 23, 31, 13, 224258, tzinfo=datetime.timezone.utc)),
        ),
    ]
