# Generated by Django 4.2.1 on 2023-06-15 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_cadeira_professores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.comentario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 12, 8, 41, 839239, tzinfo=datetime.timezone.utc)),
        ),
    ]
