# Generated by Django 4.2.1 on 2023-06-15 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_remove_comentario_post_post_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.comentario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 12, 9, 44, 143381, tzinfo=datetime.timezone.utc)),
        ),
    ]
