# Generated by Django 4.2.1 on 2023-06-15 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_post_comentario_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.comentario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
