# Generated by Django 4.2.1 on 2023-06-15 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_post_comentario_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 13, 8, 57, 165499, tzinfo=datetime.timezone.utc)),
        ),
    ]
