# Generated by Django 4.2.1 on 2023-06-15 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_post_comentario_alter_post_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 15, 13, 14, 2, 635353, tzinfo=datetime.timezone.utc)),
        ),
    ]
